# 1. Deep Learning with PyTorch - A 60 Minute Blitz 
## 2. AUTOGRAD: AUTOMATIC DIFFERENTIATION

Practice!

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

### Tensor

In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
print(x.grad_fn)

None


In [4]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place.

In [7]:
a = torch.randn(2,2)
print(a)
a = ((a*3) / (a-1))
print(a)
print(a.requires_grad)
b = (a*a).sum()
print(b)
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

tensor([[ 0.3596,  0.4314],
        [ 0.4551, -1.5501]])
tensor([[-1.6846, -2.2758],
        [-2.5053,  1.8236]])
False
tensor(17.6188)
None
True


### Gradients

In [8]:
print(x.grad)

None


In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
out.backward()

d(out)/dx

In [11]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [12]:
x = torch.randn(3, requires_grad=True)
y=x*2
print(y)
print(y.data)
print(y.data.norm())
while y.data.norm() < 1000:
    y = y*2
print(y)

tensor([0.9489, 2.8289, 0.5977], grad_fn=<MulBackward0>)
tensor([0.9489, 2.8289, 0.5977])
tensor(3.0431)
tensor([ 485.8621, 1448.4088,  305.9981], grad_fn=<MulBackward0>)


In [13]:
v = torch.tensor([0.1, 1., 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [14]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
